# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

conda:
  environment: envs/environment.yml

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"
  jobs:
    pre_build:
      - uses: pyvista/setup-headless-display-action@main
        with:
          qt: false
          pyvista: true
      - name: install pip requirements
        run: |
          pip install --upgrade myst_parser sphinx_gallery SQLAlchemy sphinxcontrib-matlabdomain sphinx_rtd_theme sphinx_copybutton memory_profiler
          sphinx-apidoc -f -o docs/references -e -T -t docs/_templates .

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf