name: preprocess
channels:
  - defaults
  - conda-forge
dependencies:
  - python<3.10
  - pip
  - numpy
  - matplotlib
  - scipy
  - pandas
  - tqdm
  - nipype
  - mne
  - mne-bids
  - EDFlib-Python
  - pip:
    - -r requirements.txt