name: preprocess
channels:
  - conda-forge
  - defaults
dependencies:
  - python<3.11
  - pip
  - numpy
  - matplotlib
  - scipy
  - pandas
  - joblib
  - tqdm
  - mne
  - mne-bids
  - pip:
    - -r requirements.txt