function articulatorData = getDataByArticulator(data, phonemeTrial, phonemePos)
    % Groups data in channels x trials x timepoints to a cell array where each
    % cell contains the channels x trials x timepoints for a articulator class
    %defined by the phoneme of the trial
    %
    % Input:
    % data - ieeg data channels x trials x timepoints
    % phonemeTrial - phonemeTrialParser object generated by phonemeTrialParser.m
    % phonemePos - Position of phonemes to group by (1, 2, or 3)
    % 
    % Output:
    % articulatorData - n x 1 cell array where n is the number of phonemes and each
    % cell contains the channels x trials x timepoints for a specific phoneme
    % ex. cell 1 corresponds to data for 'a', 2 corresponds to 'ae', etc.
    numArt = length(unique(phonemeTrial.phonemeClass(:,phonemePos)));
    articulatorData = cell(numArt,1);
    for iArt = 1:numArt
        artTrials = find(phonemeTrial.phonemeClass(:,phonemePos) == iArt);
        articulatorData{iArt} = data(:, artTrials, :);
    end