function phonemeData = getDataByPhoneme(data, phonemeTrial, phonemePos)
    % Groups data in channels x trials x timepoints to a cell array where each
    % cell contains the channels x trials x timepoints for a specific phoneme
    %
    % Input:
    % data - ieeg data channels x trials x timepoints
    % phonemeTrial - phonemeTrialParser object generated by phonemeTrialParser.m
    % phonemePos - Position of phonemes to group by (1, 2, or 3)
    % 
    % Output:
    % phonemeData - n x 1 cell array where n is the number of phonemes and each
    % cell contains the channels x trials x timepoints for a specific phoneme
    % ex. cell 1 corresponds to data for 'a', 2 corresponds to 'ae', etc.
    numPhones = length(unique(phonemeTrial.phonemeUnit(:,phonemePos)));
    phonemeData = cell(numPhones,1);
    for iPhone = 1:numPhones
        phoneTrials = find(phonemeTrial.phonemeUnit(:,phonemePos) == iPhone);
        phonemeData{iPhone} = data(:, phoneTrials, :);
    end

