function formatTicks(gca)
    set(gca,'FontSize',10);
    axis square
    set( gca                       , ...
        'FontName'   , 'Arial' );    
    set(gca, ...
      'Box'         , 'off'     , ...
      'TickDir'     , 'out'     , ...
      'TickLength'  , [.02 .02] , ...
      'XMinorTick'  , 'off'      , ...
      'YMinorTick'  , 'off'      , ...
      'YGrid'       , 'off'      , ...
      'LineWidth'   , 1         );
end