name: ieeg-dev
channels:
  - conda-forge
dependencies:
  - python<3.13
  - pip
  - numpy
  - matplotlib
  - scipy
  - scikit-image
  - pandas
  - numba
  - vtk[version>=9.2,build=*osmesa*]
  - mesalib
  - pyvistaqt
  - mne
  - joblib
  - qtpy
  - pip:
    - -r ../requirements.txt
    - -r testing-reqs.txt