name: ieeg-dev
channels:
  - conda-forge
dependencies:
  - python<3.13
  - pip
  - numpy
  - matplotlib
  - scipy
  - scikit-image
  - pandas
  - numba
  - pyvistaqt
  - mne
  - mne-bids
  - joblib
  - qtpy
  - pybids
  - nipype
  - EDFlib-Python
  - psutil
  - pytz
  - h5io
  - dipy
  - ipympl
  - pip:
    - naplib
