name: ieeg-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python<3.13
  - pip
  - numpy
  - matplotlib
  - scipy
  - scikit-image
  - pandas
  - numba
  - vtk>=9.2=*osmesa*
  - mesalib
  - pyvistaqt
  - mne
  - joblib
  - pip:
    - -r ../requirements.txt
    - -r testing-reqs.txt