# This workflow will install Python dependencies, run tests and lint with pycodestyle
name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        os: [ubuntu-latest, ubuntu-18.04, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: envs/environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - name: Display environment
        run: |
          conda info
          conda list
      - name: Test with pytest
        run: |
          pytest -v --pycodestyle